# Generated by Django 2.2.6 on 2019-11-06 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_mail', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
